# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Wk6_Model_Python.py
# Created on: 2018-11-14 15:48:54.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
LondonWards = "N:\\GIS\\wk6\\Week6_Practicle.gdb\\LondonWards"
contig_swm = "N:\\GIS\\wk6\\contig.swm"
MoransContig = "N:\\GIS\\wk6\\Week6_Practicle.gdb\\MoransContig"
Index_Field_Name = "LMiIndex"
ZScore_Field_Name = "LMiZScore"
Probability_Field = "LMiPValue"
Cluster-Outlier_Type = "COType"
Source_ID = "ID"
Gearys_Contig = "N:\\GIS\\wk6\\Week6_Practicle.gdb\\Gearys_Contig"
Results_Field = "GiZScore"
Probability_Field__2_ = "GiPValue"
Source_ID__2_ = "ID"
invidist_swm = "N:\\GIS\\wk6\\invidist.swm"
Geary_Individist = "N:\\GIS\\wk6\\Week6_Practicle.gdb\\Geary_Individist"
Results_Field__2_ = "GiZScore"
Probability_Field__3_ = "GiPValue"
Source_ID__3_ = "ID"
neighbour_swm = "N:\\GIS\\wk6\\neighbour.swm"
Geary_Neighbour = "N:\\GIS\\wk6\\Week6_Practicle.gdb\\Geary_Neighbour"
Results_Field__3_ = "GiZScore"
Probability_Field__4_ = "GiPValue"
Source_ID__4_ = "ID"
Moran_Neighbour = "N:\\GIS\\wk6\\Week6_Practicle.gdb\\Moran_Neighbour"
Index_Field_Name__2_ = "LMiIndex"
ZScore_Field_Name__2_ = "LMiZScore"
Probability_Field__5_ = "LMiPValue"
Cluster-Outlier_Type__2_ = "COType"
Source_ID__5_ = "ID"
Morans_InviDist = "N:\\GIS\\wk6\\Week6_Practicle.gdb\\Morans_InviDist"
Index_Field_Name__3_ = "LMiIndex"
ZScore_Field_Name__3_ = "LMiZScore"
Probability_Field__6_ = "LMiPValue"
Cluster-Outlier_Type__3_ = "COType"
Source_ID__6_ = "ID"

# Process: Generate Spatial Weights Matrix
arcpy.GenerateSpatialWeightsMatrix_stats(LondonWards, "ID", contig_swm, "CONTIGUITY_EDGES_CORNERS", "EUCLIDEAN", "1", "", "0", "ROW_STANDARDIZATION", "", "", "", "")

# Process: Cluster and Outlier Analysis (Anselin Local Morans I)
arcpy.ClustersOutliers_stats(LondonWards, "AvgGCSE201", MoransContig, "GET_SPATIAL_WEIGHTS_FROM_FILE", "EUCLIDEAN_DISTANCE", "NONE", "", contig_swm, "NO_FDR")

# Process: Hot Spot Analysis (Getis-Ord Gi*)
arcpy.HotSpots_stats(LondonWards, "AvgGCSE201", Gearys_Contig, "GET_SPATIAL_WEIGHTS_FROM_FILE", "EUCLIDEAN_DISTANCE", "NONE", "", "", contig_swm, "NO_FDR")

# Process: Generate Spatial Weights Matrix (3)
arcpy.GenerateSpatialWeightsMatrix_stats(LondonWards, "ID", invidist_swm, "INVERSE_DISTANCE", "EUCLIDEAN", "1", "", "0", "ROW_STANDARDIZATION", "", "", "", "")

# Process: Hot Spot Analysis (Getis-Ord Gi*) (2)
arcpy.HotSpots_stats(LondonWards, "AvgGCSE201", Geary_Individist, "GET_SPATIAL_WEIGHTS_FROM_FILE", "EUCLIDEAN_DISTANCE", "NONE", "", "", invidist_swm, "NO_FDR")

# Process: Generate Spatial Weights Matrix (2)
arcpy.GenerateSpatialWeightsMatrix_stats(LondonWards, "ID", neighbour_swm, "K_NEAREST_NEIGHBORS", "EUCLIDEAN", "1", "", "8", "ROW_STANDARDIZATION", "", "", "", "")

# Process: Hot Spot Analysis (Getis-Ord Gi*) (3)
arcpy.HotSpots_stats(LondonWards, "AvgGCSE201", Geary_Neighbour, "GET_SPATIAL_WEIGHTS_FROM_FILE", "EUCLIDEAN_DISTANCE", "NONE", "", "", neighbour_swm, "NO_FDR")

# Process: Cluster and Outlier Analysis (Anselin Local Morans I) (2)
arcpy.ClustersOutliers_stats(LondonWards, "AvgGCSE201", Moran_Neighbour, "GET_SPATIAL_WEIGHTS_FROM_FILE", "EUCLIDEAN_DISTANCE", "NONE", "", neighbour_swm, "NO_FDR")

# Process: Cluster and Outlier Analysis (Anselin Local Morans I) (3)
arcpy.ClustersOutliers_stats(LondonWards, "AvgGCSE201", Morans_InviDist, "GET_SPATIAL_WEIGHTS_FROM_FILE", "EUCLIDEAN_DISTANCE", "NONE", "", invidist_swm, "NO_FDR")

